[accesslog]
[api]
  #insecure=true
  dashboard=true
  debug=true
[log]
  level="INFO"
[entryPoints]
  [entryPoints.xavki]
    address=":80"

  [entryPoints.api]
    address=":8080"
[providers.file]
  directory = "/home/vagrant/services/"             
  watch = true

