[accesslog]
[api]
  insecure=true
  dashboard=true
  debug=true
[log]
  level="INFO"
[entryPoints]
  [entryPoints.xavki]
    address=":80"

[providers.file]
  directory = "/home/vagrant/services/"             
  watch = true

[providers.docker]
  endpoint = "ssh://vagrant@192.168.13.11:22"
