[accesslog]
[api]
  insecure=true
  dashboard=true
  debug=true
[log]
  level="INFO"
[entryPoints]
  [entryPoints.xavki]
    address=":80"
  [entryPoints.mysql]
    address=":3306"
[providers.docker]
  endpoint = "ssh://vagrant@192.168.13.11:22"
  useBindPortIP = true
