[accesslog]
[api]
  insecure=true
  dashboard=true
  debug=true
[log]
  level="INFO"
[entryPoints]
  [entryPoints.xavki]
    address=":80"
    [entryPoints.xavki.http.redirections]
      [entryPoints.xavki.http.redirections.entryPoint]
        to = "xavki_secure"
        scheme = "https"
  [entryPoints.xavki_secure]
    address=":443"

[providers.file]
  directory = "/home/vagrant/services/"             
  watch = true

