[http]
  [http.routers]
    [http.routers.xavki_route]
      entryPoints = ["xavki_secure"]
      service = "xavki"
      rule = "Host(`drive.xavki.fr`) && Path(`/`)"
      middlewares = ["xavki_https"]
      [http.routers.xavki_route.tls]
        certResolver = "xavki_certs"
        options = "intermediate"
  [http.middlewares]
    [http.middlewares.xavki_https.redirectScheme]
      scheme = "https"
      permanent = true
  [http.services]
    [http.services.xavki]
      [http.services.xavki.loadBalancer]
        [[http.services.xavki.loadBalancer.servers]]
          url = "http://192.168.1.17:8081"

[tls.options]
  [tls.options.intermediate]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    ]

